apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: nyplex/chat-users
          env:
            - name: MONGO_URI
              value: "mongodb://users-mongo-srv:27017/users"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: JWT_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: JWT_REFRESH_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: chat

---
apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      port: 3000
      targetPort: 3000
